<?php

namespace App\Http\Middleware;

use App\Exceptions\BusinessException;
use App\util\CodeResponse;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{
    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param $request
     * @return string|null
     */
    protected function redirectTo($request): ?string
    {
        if (! $request->expectsJson()) {
            return route('login');
        }
    }

    /**
     * @param $request
     * @param array $guards
     * @throws BusinessException
     * @throws AuthenticationException
     */
    protected function unauthenticated($request, array $guards)
    {
        if($request->expectsJson() || in_array('wx', $guards)) {
            throw new BusinessException(CodeResponse::NOT_LOGIN);
        }
        parent::unauthenticated($request, $guards); // TODO: Change the autogenerated stub
    }
}
